# Generated by Django 5.0.1 on 2026-05-04 05:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_authsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacySyncOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'legacy_sync_outbox',
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='identity_outbox_status_retry'), models.Index(fields=['path', 'status'], name='identity_outbox_path_status')],
            },
        ),
    ]
