# Generated by Django 5.0.1 on 2026-05-16 05:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0004_legacysyncoutbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMFASettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("mfa_enabled", models.BooleanField(default=False)),
                ("mfa_secret_encrypted", models.TextField(blank=True, null=True)),
                ("pending_mfa_secret_encrypted", models.TextField(blank=True, null=True)),
                ("mfa_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("last_used_totp_step", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_mfa_settings",
                "indexes": [
                    models.Index(fields=["locked_until"], name="identity_mfa_locked_until"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MFAChallenge",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("challenge_token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("login", "Login"), ("enrollment", "Enrollment")],
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mfa_challenges",
                "indexes": [
                    models.Index(fields=["user", "purpose", "used_at"], name="identity_mfa_challenge_user"),
                    models.Index(fields=["expires_at"], name="identity_mfa_challenge_exp"),
                ],
            },
        ),
    ]
